### ISSUE TITLE
webSignupConfirmation GraphQL query generating 500 errors in Gambit

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#493] opened 2019-04-05 14:31 UTC
_BUG_
-------------------
#### Current Behavior
- When Gambit receives a web signup request and the campaign does not have a `webSignup` topic setup, it errors out with a 500 error that seems to come from GraphQL.

#### Desired Behavior
- When Gambit receives a web signup request. It should be able to ignore if the campaign has no `webSignup` topic setup in Contentful.

#### Steps to Replicate
- Send a web signup request to a member with a campaign with no `webSignup` topic setup in Contentful.

#### Why This Matters
Yesterday (April 4th, 2019), we experienced an uptick in traffic in web that generated a high amount of signup requests. This requests failed each time, creating a monitoring alert due to the re-trying mechanisms in Blink.

Part of the actions taken was to shutdown the Blink worker that processes web signup confirmations. Confirmed with PM and Staff Engineer that this was a good course of action since the desired behavior is to actually ignore the requests.

#### Relevant Screenshots + Links
- [Alert & investigation](https://dosomething.slack.com/archives/C02BBP0CU/p1554402435039800)
- [Sample of the error in Papertrail](https://papertrailapp.com/systems/gambit-conversations-prod/events?focus=1050552943457882113&selected=1050552943457882113)

**Comment by rapala61** [comment] 2019-04-08 14:26
Mon, April 8th.

Since we discovered the uptick in phoenix-next signup confirmation request to Gambit last Thursday April 4th. There have been 6,390+ requests queued to be relayed. This high amount of signups over the weekend seems suspicious to me, but I don't have solid numbers to compare if it's indeed way up in comparison. What makes the errors generated by these requests suspicious is that I did not find any instance of the errors in Gambit prior to April 4th in Papertrail. They just started happening in April 4th.

Link to the April 4th discussion on this failed requests. https://dosomething.slack.com/archives/C02BBP0CU/p1554405662042000

**Comment by rapala61** [comment] 2019-04-08 14:29
The last deploy to Gambit Production was on April 1st. This excludes a deployed change in Gambit as the possible culprit of this errors since we would have expected to see instances of them dating back to April 1st.

**Comment by ngjo** [comment] 2019-04-08 15:01
Could it be related this this graphql change? https://dosomething.slack.com/archives/C02BBP0CU/p1554396420036500 Know that we had to make changes on production here https://dosomething.slack.com/archives/C03T8SDJJ/p1554478464009100

**Comment by rapala61** [comment] 2019-04-08 15:15
Re: 
>Could it be related this this graphql change? https://dosomething.slack.com/archives/C02BBP0CU/p1554396420036500 Know that we had to make changes on production here https://dosomething.slack.com/archives/C03T8SDJJ/p1554478464009100

I don't think that specific problem is related to these uptick in signup confirmation requests, however, this other 🐛 that was just patched today might be https://github.com/DoSomething/graphql/pull/97, but I haven't really looked into it.

**Comment by ngjo** [comment] 2019-04-08 15:45
Yup, just wanted to flag it because that GraphQL change happened on April 4!

**Comment by rapala61** [comment] 2019-04-08 16:18
🤔 Definitely suspicious! I was referring to the URL change specifically. There could have been some other changes deployed in tandem with that PR that is causing this.

**Comment by rapala61** [comment] 2019-07-30 23:37
@DFurnes It's been a few months since the Signup relay worker was stopped in Blink. We should add a rainy day Platform card to patch this small but annoying problem. I have to manually purge the signup relay worker every so often so it doesn't accumulate too many messages. 

A bigger question is if we are killing these SMS signup confirmation texts completely. I remember I read some conversation about this possibility @ngjo @aaronschachter .

**Comment by DFurnes** [comment] 2019-07-31 18:35
@rapala61 Thanks for following up on this! I can create a ticket once we've figured out whether we want to address this specific bug in Gambit or by disabling this functionality altogether.

**Comment by ngjo** [comment] 2019-08-01 16:09
I wouldn't remove this functionality yet, I know that the team wanted to consider ways to use this trigger to better engage/onboard a user to the action. I'll bring it up again -- it'd be useful to understand what the lift would be to address the bug so that we can compare against the value of them using it.

**Comment by aaronschachter** [comment] 2020-04-17 22:04
I was testing locally yesterday by passing `campaignId` values that don't have Gambini `campaign` entries, and kept getting a 204 status, not a 500 status as this issue would suggest should happen. This might have been fixed by the way of https://github.com/DoSomething/graphql/pull/103, where we stopped caching the list of `webSignupConfirmation` items in GraphQL, and the resulting changes in https://github.com/DoSomething/gambit/pull/505.

Digging a little deeper to try to find exactly what the problem is and leaving these notes here for now:

* https://github.com/DoSomething/graphql/pull/47 - stitches the `webSignupConfirmation` to a Rogue `campaign`, which sounds like it could cause the bug this issue was opened for

* https://github.com/DoSomething/gambit/pull/467 is the PR that began querying GraphQL for signup confirmations instead of the long-dead [Gambit Content/Campaigns](http://github.com/dosomething/gambit-content) application. Hard to know when we stopped setting the web signup confirmation messages in general though, whether it was before we deprecated Gambit Content.

**Comment by rapala61** [comment] 2020-06-03 17:33
@aaronschachter based on the last iteration of working around this reported bug. Should we close this?

**Comment by aaronschachter** [comment] 2020-06-03 17:46
Sounds like it! The signup confirmation messages have been on for a while now.

**Closed by aaronschachter** 2020-06-03 17:46 UTC
Labels: Priority (High), bug
