### ISSUE TITLE
Backfill users affected by CGG bug 

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/gambit#768] opened 2016-12-08 18:50 UTC
_BUG_
-------------------
#### Current Behavior
- 958 new users that came to us from CGG texted in keyword to sign up for Say It With The Stars received an error message. They were unable to sign up for the campaign because they did not have a phoenix account. 

#### Desired Behavior
- New user votes on CGG, has phoenix account created for them, and is able to sign up for / complete campaigns via SMS 
- We need to backfill these users so that they all have phoenix accounts. 

#### Why This Matters
- so that the new users who were affected by the CGG bug are able to sign up for/complete campaigns via SMS

#### Relevant Screenshots + Links

https://dosomething.slack.com/archives/gambit/p1481134558000024

**Comment by jamjensen** [comment] 2016-12-08 18:51
User does not have Northstar account, which broke backfill script: 

https://dosomething.slack.com/archives/gambit/p1481222930000029

**Comment by deadlybutter** [comment] 2016-12-08 19:08
These users have broken links and/or missing accounts which were unable to be auto fixed 

https://dosomething.slack.com/archives/gambit/p1481223943000048

**Comment by aaronschachter** [comment] 2017-01-23 18:31
@deadlybutter Is this resolved? (and is it a duplicate of #769?)

**Closed** 2017-01-23 19:55 UTC
