### ISSUE TITLE
Gambit timeouts during SMS Broadcasts and Niche Import

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/gambit#810] opened 2017-03-09 22:41 UTC
#### Description
- We've recently seen a spike in request timeouts, which most often happens after we send SMS broadcasts or when we import niche users.  The app crashes and the user receives the mdata error response message.  

- Heroku outlines potential causes of request timeouts here: https://devcenter.heroku.com/articles/request-timeout#timeout-behavior 

- Potential solutions include background jobs, which Heroku outlines here: https://devcenter.heroku.com/articles/background-jobs-queueing

Refs #704

**Comment by jamjensen** [comment] 2017-03-13 18:36
![](https://github.trello.services/images/mini-trello-icon.png) [GAMBIT: Investigate solutions for timeout requests](https://trello.com/c/nATpa5UU/293-gambit-investigate-solutions-for-timeout-requests)

**Comment by jamjensen** [comment] 2017-03-13 18:36
![](https://github.trello.services/images/mini-trello-icon.png) [GAMBIT: Investigate solutions for timeout requests](https://trello.com/c/nATpa5UU/293-gambit-investigate-solutions-for-timeout-requests)

**Comment by jamjensen** [comment] 2017-03-15 15:43
*Notes from the Gambit Request Timeout Meeting*

AS: "Hunch is that the culprit = external calls to Phoenix / Northstar"
MH: "New Relic would show us how calls are affecting gambit performance"

When understanding the issue, biggest things to look for are:
- What slows down NS, Phoenix and the app 

Examples of users with calls taking >30 seconds:
1. 95% of transaction cost is talking to contentful... if we're hitting stuff hard on contentful we should look into why a call to contentful would take that long.... AS: "can be two calls to contentful bc the keywords and campaigns live in separate documents... if KW comes in during incoming request then when we render the message we query contentful to see if it has a field set in campaign flow, if not then query again for the default campaign." MH: "possibly that these are one offs." 

2. Post to the signups endpoint: MH "really long request to NS for user ID... signing them up for a campaign or pulling their info (i.e. phone number)... why is it taking over 30 seconds?

- RP: "My theory is that the endpoint itself doesn't become unstable but rather the application. Would be good to know if we're stressing the system in a different way... e.g. If I generate as many requests as my computer can handle, but it wasn't because MoCo could send them to me but rather than my computer couldn't handle it.. so it's possible that we're stressing our only dyno." 

*Takeaways:*
1. Slow requests to contentful (why would a request to your super fast CDN take so long?)
2. NS gets bogged down

*Next Steps:*
1. Set up autoscaling 
2. Analyze timeouts in New Relix
3. If timeouts persist, fire up a third dyno

**Comment by aaronschachter** [comment] 2017-03-27 18:49
I think it's safe to rename this as "timeouts" instead of crashes. The app crashes seem to have been caused by #811.

**Comment by rapala61** [comment] 2017-03-27 20:18
While load testing Gambit thor, it became apparent to me that using an aggressive concurrency setting ended in a high error rate of requests made to Northstar thor.

**Comment by aaronschachter** [comment] 2017-03-29 16:38
Today's broadcast doesn't seem to support the theory that it's always an external request that causes this. We started receiving the `Connection failed. Errno::ETIMEDOUT CC: 2. E: ''` emails from [mData failures](https://secure.mcommons.com/mdatas/13720/mdata_queries). I checked Heroku logs to find plenty of H12's:

```
 at=error code=H12 desc="Request timeout" method=POST path="/v1/chatbot" host=ds-mdata-responder.herokuapp.com request_id=29da5ad4-257a-4ee7-81d8-2d099b6b81be fwd="64.22.127.231" dyno=web.2 connect=1ms service=30000ms status=503 bytes=0 protocol=https
```

In [New Relic](https://rpm.newrelic.com/accounts/108038/applications/25522350/transactions#id=5b225765625472616e73616374696f6e2f457870726573736a732f504f53542f2f76312f63686174626f742f222c22225d) from what I can tell -- it seems to be a problem within Node today vs Phoenix [timeouts](https://github.com/DoSomething/phoenix/issues/7333):

<img width="1208" alt="screen shot 2017-03-29 at 9 23 30 am" src="https://cloud.githubusercontent.com/assets/1236811/24465440/dc96ca90-1461-11e7-9b8e-edbf6725b82a.png">

I restarted all dynos, and the H12's stop -- but it seems that broadcast triggered them in the first place. Today's broadcast went out to 30k members.

**Comment by aaronschachter** [comment] 2017-03-29 17:04
From [Heroku docs defining a H12](https://devcenter.heroku.com/articles/error-codes#h12-request-timeout):
> An HTTP request [took longer than 30 seconds](https://devcenter.heroku.com/articles/request-timeout) to complete ... This 30-second limit is measured by the router, and includes all time spent in the dyno, including the kernel’s incoming connection queue and the app itself.

From https://devcenter.heroku.com/articles/request-timeout:
> When a timeout is detected the router will return a customizable error page to the client and an H12 error is emitted to your application logs. While the router has returned a response to the client, **your application will not know that the request it is processing has reached a time-out, and your application will continue to work on the request**. To avoid this situation Heroku recommends setting a timeout within your application and keeping the value well under 30 seconds, such as 10 or 15 seconds. Unlike the routing timeout, these timers will begin when the request begins being processed by your application. You can read more about this below in Timeout behavior.

From https://devcenter.heroku.com/articles/request-timeout#debugging-request-timeouts, numerous database queries (which we do, by writing/reading`signup` documents for each request) as well as numerous API queries (which we've already documented we do) could be a culprit.

Here's ideas for next steps:

* Per https://github.com/DoSomething/gambit/issues/810#issuecomment-286783237, a next step for the immediate future might be to try a 3rd dyno. 
    * Related: Experiment with the number of members we send a single broadcast to, to better determine what # of requests cause the H12's. 

* Set a timeout in Gambit to 30 seconds to anticipate (and prevent) H12 errors.
    * This brings to mind the idea returning a response of "200 OK" as soon as we receive a request as a quick way to avoid H12's immediately (https://github.com/DoSomething/gambit/issues/704#issuecomment-275727492). Not sure if this affects our New Relic metrics (but we can use the Gambit Local and Thor apps to see)

* It might be time to start thinking about working on background tasks with Blink.

**Comment by rapala61** [comment] 2017-03-29 17:23
We could experiment with setting a timeout setting on our HTTP lib of say 20 seconds (to prevent any race condition between Timeout settings at Heroku and MoCo). We should probably pair that with a message to the user to try again later. There are a few things that are not so straight forward with this since external calls do have side effects (like posting a sign up) and we do not have a way to rollback in case a later step times out.

**Comment by aaronschachter** [comment] 2017-03-29 17:27
I created https://github.com/DoSomething/gambit/issues/776 from https://github.com/DoSomething/gambit/issues/810#issuecomment-286783237 but closed it as a "this doesn't happen a lot" but a look at https://secure.mcommons.com/mdatas/13720/mdata_queries (instead of just relying on the email alerts sent from Mobile Commons) shows this still happens a lot.

I'm thinking it might be our best bet for stopping these H12's any time soon (or trying out that 3rd dyno). 

A problem still though is that we can't (or at least I'm not sure how) replicate a broadcast locally -- @rafa would it make sense to start a wiki page (or add to one of the existing Testing/Tests pages) to document how you've gone about load testing?

**Comment by rapala61** [comment] 2017-03-29 17:33
I'm not sure how the third Dyno would help. There is a big chance the problem gets worst by just sending more concurrent connections to Northstar/Phoenix-Ashes, thus increasing timeouts.

I'll definitely document load testing.

**Comment by aaronschachter** [comment] 2017-03-30 01:06
Tonight's broadcast to 30k members hasn't triggered any H12 errors (knocking on wood). We're at 13% memory usage and slowly increasing... when Gambit was timing out earlier today we were at 17% (and [restarting dynos made H12's disappear](https://github.com/DoSomething/gambit/issues/810#issuecomment-290148244r) -- see Heroku metrics below)

<img width="1200" alt="screen shot 2017-03-29 at 6 03 23 pm" src="https://cloud.githubusercontent.com/assets/1236811/24483030/5631225e-14aa-11e7-975f-988a3f76abd8.png">

**Comment by aaronschachter** [comment] 2017-05-01 19:52
Per work done in #849, the chatbot endpoint will return a 504 if a request is taking too long (#704).

Per this afternoon, our production mData chatbot now posts incoming messages to Blink instead of Gambit. Blink posts the incoming mData request to Gambit and will retry it again if it receives a 504.

**Closed** 2017-05-01 19:51 UTC
